services:
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   hostname: api
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: "160MB"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shopper
    ports:
      - "5432:5432"
    volumes:
      - ./api/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "160MB"
