services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shopper
    ports:
      - "5432:5432"
    volumes:
      - ./api/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  front:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: front
    restart: always
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_started

networks:
  default:
    driver: bridge
